<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/empleadoForm.js') ?>"></script>

<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Añade un nuevo Empleado:</h1>
                <p>Aqui podras añadir un nuevo empleado a la biblioteca</p>
            </div>
         <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
 					$form->setAttribute('action', $this->url('empleados', array('action' => 'index')));
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'empleadoForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='emp_nombre' class='col-sm-2 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('emp_nombre')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Nombre')->setAttribute('id', 'emp_nombre'));

							echo "</div>";
						echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='emp_apellido' class='col-sm-2 control-label'><span>Apellido: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('emp_apellido')->setAttribute('class', 'form-control')->setAttribute('id', 'emp_apellido')->setAttribute('placeholder', 'Apellido'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='email' class='col-sm-2 control-label'><span>Email: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('email')->setAttribute('class', 'form-control')->setAttribute('id', 'email')->setAttribute('placeholder', 'Email'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='password' class='col-sm-2 control-label'><span>Contraseña: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('password')->setAttribute('class', 'form-control')->setAttribute('id', 'password')->setAttribute('placeholder', 'Password'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='estatus' class='col-sm-2 control-label'><span>Estatus: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('estatus')->setAttribute('class', 'form-control')->setAttribute('id', 'estatus'));

							echo "</div>";
						 echo "</div>";


					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-3 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Añadir Empleado'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>
        </div>
    </div>
