<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h2>¿Estas seguro de eliminar este Empleado?</h2>
                <p>Empleado #<?php echo $this->escapeHtml($this->aut_id); ?>
     			</p>
     			<p>Nombre: <?php echo $this->escapeHtml($autor->emp_nombre).' '.$this->escapeHtml($autor->emp_nombre)?> 
</p>

     			<?php 

				 	$url = $this->url('empleado', array(
				    'action' => 'delete',
				    'id'     => $this->emp_id,
				 	));

     			 ?>

     			<form action="<?php echo $url; ?>" method="post">
				 	<div>
				     	<input type="hidden" name="id" value="<?php echo (int) $empleado->emp_id; ?>" />
				     	<input type="submit" class="btn btn-primary" name="del" value="Eliminar" />
				     	<input type="submit" class="btn btn-default" name="del" value="Cancelar" />
				 	</div>
				</form>
                
            </div>
        </div>
    </div>
