<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/empleadoForm.js') ?>"></script>


<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Modifica un empleado:</h1>
                <p>Aqui podras modificar datos de cualquier empleado asociado a la biblioteca.</p>

                <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
         			/*$form = $this->form;*/
 					$form->setAttribute('action', $this->url('empleados', array('action' => 'edit', 'id'=> $this->id)));


 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'empleadoForm');

 					$form->prepare();
 					$form->get('submit')->setAttribute('value', 'Guardar cambios');

					echo $this->form()->openTag($form);
					
					echo "<div class='form-group'>";
						echo "<label for='emp_nombre' class='col-sm-2 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('emp_nombre')->setAttribute('class', 'form-control')->setAttribute('id', 'aut_nombre'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='emp_apellido' class='col-sm-2 control-label'><span>Apellido: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('emp_apellido')->setAttribute('class', 'form-control')->setAttribute('id', 'emp_apellido'));

							echo "</div>";
						 echo "</div>";


					echo "<div class='form-group'>";
						echo "<label for='email' class='col-sm-2 control-label'><span>email: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('email')->setAttribute('class', 'form-control')->setAttribute('id', 'email'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='estatus' class='col-sm-2 control-label'><span>Estatus: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('estatus')->setAttribute('class', 'form-control')->setAttribute('id', 'estatus'));

							echo "</div>";
						 echo "</div>";

					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-2 col-sm-10'>";

							echo $this->formSubmit($form->get('submit'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>

            </div>
        </div>
    </div>
