<?php  

	/*require_once($this->basePath('/tcpdf/config/lang/eng.php'));
	require_once($this->basePath('/tcpdf/tcpdf.php'));*/

	require_once('/tcpdf/config/lang/eng.php');
	require_once('/tcpdf/tcpdf.php');
	

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Biblioteca Maria Quesadaa');
$pdf->SetTitle('Reporte de Empleados');
$pdf->SetSubject('Reportes');
$pdf->SetKeywords('Reporte, Empleados, php, mysql');


$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

//set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

//set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

//set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

//set some language-dependent strings
$pdf->setLanguageArray($l);

// ---------------------------------------------------------

// set default font subsetting mode
$pdf->setFontSubsetting(true);

$pdf->SetFont('helvetica', '', 9, '', true);

// Add a page 
// This method has several options, check the source code documentation for more information.
$pdf->setPrintHeader(false); //no imprime la cabecera ni la linea 
$pdf->setPrintFooter(true); // imprime el pie ni la linea 
$pdf->AddPage();

//*************
  ob_end_clean();//rompimiento de pagina


$html='<div align="right">Fecha: '.date('d-m-Y').'</div>
		<div align="right"> Hora: '.date('h:i:sa').'</div>
<div align="center">
			<h3>Biblioteca Maria Quesada</h3>
			<h1>Lista de Empleados</h1>
			<br /><br />			
			<table border="1" bordercolor="#0000CC" bordercolordark="#FF0000">';	

			$html=$html.'<tr bgcolor="#FF0000">
			<td><font color="#FFFFFF">Id</font></td>
			<td><font color="#FFFFFF">Nombre</font></td>
			<td><font color="#FFFFFF">Email</font></td>
			<td><font color="#FFFFFF">Estatus</font></td>
			</tr>';

			foreach ($empleados as $empleado) :
				
				/*$html=  $html.'<tr bgcolor="#95B1CE">';*/
			
				$html=$html.'<tr>';
				$html = $html.'<td>';
				$html = $html. $this->escapeHtml($empleado->emp_id);
				$html = $html.'</td><td>';
				$html = $html. $this->escapeHtml($empleado->emp_nombre).' '. $this->escapeHtml($empleado->emp_apellido);
				$html = $html.'</td><td>';
				$html = $html. $this->escapeHtml($empleado->email);
				$html = $html.'</td><td>';
				$html = $html. $this->escapeHtml($empleado->estatus);
				$html = $html.'</td></tr>';		
				
			endforeach;
						
			$html=$html.'</table></div>';

$pdf->writeHTMLCell($w=0, $h=0, $x='', $y='', $html, $border=0, $ln=1, $fill=0, $reseth=true, $align='', $autopadding=true);

$pdf->Output('Reporte empleados.pdf', 'I');
?>