<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/autorForm.js') ?>"></script>

<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Añade un nuevo autor:</h1>
                <p>Aqui podras añadir un nuevo autor a la biblioteca</p>
            </div>
         <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
 					$form->setAttribute('action', $this->url('autor', array('action' => 'add')));
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'autorForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='aut_id' class='col-sm-2 control-label'><span>ID: </span></label>";
						echo '<div class="col-sm-10">';

							echo $this->formRow($form->get('aut_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'ID de autor')->setAttribute('id', 'aut_id'));

						echo "</div>";
					echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='aut_nombre' class='col-sm-2 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('aut_nombre')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Nombre')->setAttribute('id', 'aut_nombre'));

							echo "</div>";
						echo "</div>";
					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-2 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Añadir Autor'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>
        </div>
    </div>
