<div class="row">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Lista de Autores: <?php echo $this->estatus; ?></h1>
                <p>Aqui podras visualizar todos los autores que posee la biblioteca</p>
                <p><a class="btn btn-primary btn-lg" href="<?php echo $this->basePath('/autor/add') ?>" role="button">Nuevo Autor</a></p>
            </div>

            <table class="table table-hover">
			 <tr>
			     <th>#</th>
			     <th>Nombre</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($autor as $autor) : ?>
			 <tr>
			     <td><?php echo $this->escapeHtml($autor->aut_id);?></td>
			     <td><?php echo $this->escapeHtml($autor->aut_nombre);?></td>

			    <td>
			        <a href="<?php echo $this->url('autor',
			            array('action'=>'edit', 'id' => $autor->aut_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->url('autor',
			            array('action'=>'delete', 'id' => $autor->aut_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			 <?php endforeach; ?>
			 </table>
        </div>
    </div>
