<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/autorForm.js') ?>"></script>

<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Añade una Sancion:</h1>
                <p>Aqui podras añadir sanciones a los usuarios</p>
            </div>
         <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
 					$form->setAttribute('action', $this->url('sanciones', array('action' => 'add')));
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'sancionForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='aut_id' class='col-sm-3 control-label'><span>ID sancion: </span></label>";
						echo '<div class="col-sm-9">';

							echo $this->formRow($form->get('sanc_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#########')->setAttribute('id', 'sanc_id'));

						echo "</div>";
					echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='prest_id' class='col-sm-3 control-label'><span>ID prestamo: </span></label>";
							echo '<div class="col-sm-9">';

								echo $this->formRow($form->get('prest_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#########')->setAttribute('id', 'prest_id'));

							echo "</div>";
						echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='aut_nombre' class='col-sm-3 control-label'><span>ID usuario: </span></label>";
							echo '<div class="col-sm-9">';

								echo $this->formRow($form->get('user_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#########')->setAttribute('id', 'user_id'));

							echo "</div>";
						echo "</div>";

						echo "<div class='form-group'>";
						echo "<label for='aut_nombre' class='col-sm-3 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-9">';

								echo $this->formRow($form->get('user_name')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Nombre de Usuario')->setAttribute('id', 'user_name'));

							echo "</div>";
						echo "</div>";

						echo "<div class='form-group'>";
						echo "<label for='aut_nombre' class='col-sm-3 control-label'><span>Días de sancion: </span></label>";
							echo '<div class="col-sm-9">';

								echo $this->formRow($form->get('sanc_dias')->setAttribute('class', 'form-control')->setAttribute('placeholder', '##')->setAttribute('id', 'sanc_dias'));

							echo "</div>";
						echo "</div>";

						echo "<div class='form-group'>";
						echo "<label for='aut_nombre' class='col-sm-3 control-label'><span>Estado de sancion: </span></label>";
							echo '<div class="col-sm-9">';

								echo $this->formRow($form->get('sanc_estado')->setAttribute('class', 'form-control')->setAttribute('id', 'sanc_estado'));

							echo "</div>";
						echo "</div>";

					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-2 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Añadir Autor'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>
        </div>
    </div>
