<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/prestamoForm.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.11.3.custom/jquery-ui.min.js') ?>"></script>
<link rel="stylesheet" href="<?php echo $this->basePath('/js/jquery-ui-1.11.3.custom/jquery-ui.theme.min.css') ?>">
<script type="text/javascript">
	$(function() {
	$( "#fecha_salida" ).datepicker();
	$( "#fecha_salida" ).datepicker( "option", "dateFormat", 'yy-mm-dd' );
	
});
</script>
<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Registro de prestamos:</h1>
                <p>Registra los prestamos de libros en la biblioteca</p>
                
                 <a href="<?php echo $this->basePath('/usuarios/add') ?>"class="btn btn-primary btn-md" href="#" role="button">Añadir Usuario</a>
            </dixv>            
        </div>

        <div class="col-md-offset-4 col-md-5">
         		<?php
 					$form->setAttribute('action', $this->basePath('/prestamos/add') );
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'prestamosForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='prest_id' class='col-sm-2 control-label'><span>ID: </span></label>";
						echo '<div class="col-sm-8">';

							echo $this->formRow($form->get('prest_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#')->setAttribute('id', 'prest_id'));

						echo "</div>";
					echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='libro_bar_id' class='col-sm-2 control-label'><span>Libro ID: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('libro_bar_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#')->setAttribute('id', 'libro_bar_id'));

							echo "</div>";
						echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='user_id' class='col-sm-2 control-label'><span>Usuario ID: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('user_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', '#')->setAttribute('id', 'user_id'));

							echo "</div>";
						echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='fecha_salida' class='col-sm-2 control-label'><span>Salida: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('fecha_salida')->setAttribute('class', 'form-control')->setAttribute('placeholder', '0000-00-00')->setAttribute('id', 'fecha_salida'));

							echo "</div>";
						echo "</div>";
						
					/*echo "<div class='form-group'>";
						echo "<label for='fecha_devolucion' class='col-sm-2 control-label'><span>Devolucion: </span></label>";
							echo '<div class="col-sm-8">';

								echo $this->formRow($form->get('fecha_devolucion')->setAttribute('class', 'form-control')->setAttribute('placeholder', '0000-00-00')->setAttribute('id', 'fecha_devolucion'));

							echo "</div>";
						echo "</div>";*/

					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-4 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Registrar'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                ?>
         	</div>
    </div>
