<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                  <h2>¿Estas seguro de eliminar este prestamo?</h2>
                <p># Prestamo: <?php echo $this->escapeHtml($this->prest_id); ?>
     			</p>
     			<p># User id:  <?php echo $this->escapeHtml($prestamos->user_id); ?>. </p>
                <p># Libro id: <?php echo $this->escapeHtml($prestamos->libro_bar_id); ?>.</p>

     			<?php 

				 	$url = $this->url('prestamos', array(
				    'action' => 'delete',
				    'id'     => $this->prest_id,
				 	));

     			 ?>

     			<form action="<?php echo $url; ?>" method="post">
				 	<div>
				     	<input type="hidden" name="id" value="<?php echo (int) $prestamos->prest_id; ?>" />
				     	<input type="submit" class="btn btn-primary" name="del" value="Eliminar" />
				     	<input type="submit" class="btn btn-default" name="del" value="Cancelar" />
				 	</div>
				</form>

               
            </div>
        </div>
    </div>
