<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery-ui-1.11.3.custom/jquery-ui.min.js') ?>"></script>
<link rel="stylesheet" href="<?php echo $this->basePath('/js/jquery-ui-1.11.3.custom/jquery-ui.theme.min.css') ?>">
<script type="text/javascript">
	$(function() {
	$( "#fecha_salida" ).datepicker();
	$( "#fecha_salida" ).datepicker( "option", "dateFormat", 'yy-mm-dd' );
});
</script>

<div class="row" ng-controller="prestController as prestCtrl">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Préstamos por fechas:</h1>

            Buscar: <input ng-model="fecha_salida" ng-maxlength="10" id="fecha_salida" placeholder="0000-00-00">  <button class="btn btn-default" id="filtrar_salida" ng-click="setSalida();">  <span class="glyphicon glyphicon-search"></span></button>

            </div>
           
            <table class="table table-hover">
			 <tr>
			 	 <th>Salida</th>
			 	 <th>Devolución</th>
			 	 <th># Usuario</th>
			     <th># Libro</th>
			     <th>Estatus</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			
			 <tr ng-repeat="prestamo in prestamos | filter:fecha_salida | orderBy:prestamo">
			 	<td>{{prestamo.fecha_salida}}</td>
			 	<td>{{prestamo.fecha_devolucion}}</td>
			 	<td>{{prestamo.prest_id}}</td>
			    <td><a href="<?php echo $this->basePath('/libro/details/{{prestamo.libro_bar_id}}') ?>">{{prestamo.libro_bar_id}}</a></td>
			    <td>{{prestamo.estatus}}</td>
			    <td>
			        <a href="<?php echo $this->basePath('/prestamos/edit/{{prestamo.prest_id}}') ?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->basePath('/prestamos/delete/{{prestamo.prest_id}}') ?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			
			 </table>
        </div>
    </div>
