<div class="row">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Lista de Préstamos:</h1>
                <a href="<?php echo $this->basePath('/prestamos/add') ?>"class="btn btn-primary btn-lg" href="#" role="button">Registrar prestamo</a>
                <a href="<?php echo $this->basePath('/prestamos/devolucion') ?>"class="btn btn-primary btn-lg" href="#" role="button">Registrar Devolucion</a>
            </div>

            <table class="table table-hover">
			 <tr>
			     <th># Préstamo</th>
			     <th># Usuario</th>
			     <th># Libro </th>
			     <th>Salida</th>
			     <th>Devolucién</th>
			     <th>Estatus</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($prestamos as $prestamo) : ?>
			 <tr>
			    <td><?php echo $this->escapeHtml($prestamo->prest_id);?></td>
			    <td><?php echo $this->escapeHtml($prestamo->user_id);?></td>

			     <td> 
			     	<a href="<?php echo $this->basePath('libro/details/').$prestamo->libro_bar_id ?>">
			         	<?php echo $this->escapeHtml($prestamo->libro_bar_id);?>
			        </a>
			     </td>
			     <td><?php echo $this->escapeHtml($prestamo->fecha_salida);?></td>
			     <td><?php echo $this->escapeHtml($prestamo->fecha_devolucion);?></td>
			     <td><?php echo $this->escapeHtml($prestamo->estatus);?></td>
			    <td>
			        <a href="<?php echo $this->url('prestamos',
			            array('action'=>'edit', 'id' => $prestamo->prest_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->url('prestamos',
			            array('action'=>'delete', 'id' => $prestamo->prest_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			 <?php endforeach; ?>
			 </table>
        </div>
    </div>
