<div class="row">
        <div class="col-md-9" style="">                
            <div class="jumbotron">
                <h1>Maria Quesada</h1>
                <p>Escuela Básica Nacional Norman Prieto Ramos. Esta es la administración, de una simple biblioteca para todos. Múltiples libros, múltiples categorías, préstamos y mucho más.</p>

                <p><a class="btn btn-primary btn-lg" href="<?php echo $this->basePath('/prestamos/add') ?>" role="button">Nuevo Préstamo</a>
                    <a class="btn btn-default btn-lg" href="<?php echo $this->basePath('/prestamos/devolucion') ?>" role="button">Nueva Devolución</a>             
                </p>
            </div>
        </div>
        <div class="row">
        <div class="col-xs-6 col-md-3">
            <a href="#" class="thumbnail">
            <img src="<?php echo $this->basePath('/img/escudo.png') ?>" alt="Escudo de la Institucion">
            </a>
        </div>
        </div>
    </div>
