<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/usuariosForm.js') ?>"></script>

<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Añade un nuevo usuario:</h1>
                <p>Aqui podras añadir un nuevo usuario a la biblioteca</p>
            </div>
         <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
 					$form->setAttribute('action', $this->url('usuarios', array('action' => 'add')));
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'usuariosForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='aut_id' class='col-sm-2 control-label'><span>ID: </span></label>";
						echo '<div class="col-sm-10">';

							echo $this->formRow($form->get('user_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'ID de usuario')->setAttribute('id', 'user_id'));

						echo "</div>";
					echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='user_nombre' class='col-sm-2 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('user_nombre')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Nombre')->setAttribute('id', 'user_nombre'));

							echo "</div>";
						echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='user_apellido' class='col-sm-2 control-label'><span>Apellido: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('user_apellido')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Apellido')->setAttribute('id', 'user_apellido'));

							echo "</div>";
						echo "</div>";	



					echo "<div class='form-group'>";
						echo "<label for='user_nacionalidad' class='col-sm-2 control-label'><span>Nacionalidad: </span></label>";
							

								echo '<div class="input-group">';
								echo '<div class="col-sm-6">';
								echo $this->formRow($form->get('user_nacionalidad')->setAttribute('class', 'form-control')->setAttribute('id', 'user_nacionalidad'));
								echo '</div>';
								echo '<div class="col-sm-6">';
								echo $this->formRow($form->get('user_ced')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Cedula')->setAttribute('id', 'user_ced'));
								echo '</div>';
							echo "</div>";
						echo "</div>";



					echo "<div class='form-group'>";
						echo "<label for='user_ciudad' class='col-sm-2 control-label'><span>Ciudad: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('user_ciudad')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Ciudad')->setAttribute('id', 'user_ciudad'));
							echo "</div>";
						echo "</div>";

						echo "<div class='form-group'>";
						echo "<label for='user_cod_tel' class='col-sm-2 control-label'><span>Telefono: </span></label>";
							echo '<div class="input-group">';
							echo '<div class="col-sm-7">';
								echo $this->formRow($form->get('user_cod_tel')->setAttribute('class', 'form-control')->setAttribute('id', 'user_cod_tel'));
							echo '</div>';
							echo '<div class="col-sm-5">';
								echo $this->formRow($form->get('user_tel')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Telefono')->setAttribute('id', 'user_tel'));
							echo '</div>';
							echo "</div>";
						echo "</div>";	
						
					echo "<div class='form-group'>";
						echo "<label for='user_direccion' class='col-sm-2 control-label'><span>Direccion: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('user_direccion')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Direccion')->setAttribute('id', 'user_direccion'));
							echo "</div>";
						echo "</div>";

					echo "<div class='form-group'>";
						echo "<label for='user_correo' class='col-sm-2 control-label'><span>Correo: </span></label>";
							echo '<div class="col-sm-10">';
							echo '<div class="input-group">';
							echo '<span class="input-group-addon">@</span>';
								echo $this->formRow($form->get('user_correo')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Correo')->setAttribute('id', 'user_correo'));
							echo '</div>';
							echo "</div>";
						echo "</div>";


					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-5 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Añadir Usuario'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>
        </div>
    </div>
