<div class="row">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Lista de Usuarios:</h1>
                <p>Aqui podras visualizar todos los usuarios que forman parte de la biblioteca</p>
                <p><a class="btn btn-primary btn-lg" href="<?php echo $this->basePath('/usuarios/add') ?>" role="button">Nuevo Usuario</a></p>
            </div>

            <table class="table table-hover">
			 <tr>
			     <th>#</th>
			     <th>Nombre</th>
			     <th>Cedula</th>
			     <th>Telefono</th>
			     <th>Municipio</th>
			     <th>Correo</th>
			     <th>Direccion</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($usuarios as $usuario) : ?>
			 <tr>
			     <td><?php echo $this->escapeHtml($usuario->user_id);?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_nombre).' '. $this->escapeHtml($usuario->user_apellido)?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_nacionalidad).'-'.$this->escapeHtml($usuario->user_ced);?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_cod_tel).'-'.$this->escapeHtml($usuario->user_tel);?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_ciudad);?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_correo);?></td>
			     <td><?php echo $this->escapeHtml($usuario->user_direccion);?></td>


			    <td>
			        <a href="<?php echo $this->url('usuarios',
			            array('action'=>'edit', 'id' => $usuario->user_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->url('usuarios',
			            array('action'=>'delete', 'id' => $usuario->user_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			 <?php endforeach; ?>
			 </table>
        </div>
    </div>
