<div class="row" ng-controller="listController as listCtrl">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Libros por Autor:</h1>

            Buscar: <input ng-model="query.aut_nombre" ng-maxlength="10"> <span class="glyphicon glyphicon-user"></span>

			<!--Ordenar por:
			<select ng-model="orderProp">
				<option value="aut_nombre" ng-selected>Autor</option>
			  <option value="libro_nombre">Alphabetical</option>
			  <option value="libro_bar_id">Codigo</option>
			  <option value="catedra_nombre">Catedra</option>
			</select>-->
            </div>
           
            <table class="table table-hover">
			 <tr>
			     <th>Autor <span class="glyphicon glyphicon-user"></span></th>
			     <th>#</th>
			     <th>Libro <span class="glyphicon glyphicon-book"></span></th>
			 </tr>
			
			 <tr ng-repeat="libro in libros | filter:query | orderBy:aut_nombre">
			 	<td>{{libro.aut_nombre}}</td>
			    <td>{{libro.libro_bar_id}}</td>
			    <td><a href="<?php echo $this->basePath('/libro/details/{{libro.libro_bar_id}}') ?>">{{libro.libro_nombre}}</a></td>
			     
			   
			 </tr>
			
			 </table>
        </div>
    </div>
