<script type="text/javascript" src="<?php echo $this->basePath('/js/jquery.validate.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/messages_es.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('/js/editorForm.js') ?>"></script>

<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Añade una editorial:</h1>
                <p>Aqui podras añadir nuevos editores a la biblioteca</p>
            </div>

            <div class="row">
         	<div class="col-md-offset-3 col-md-6">
         		<?php
 					$form->setAttribute('action', $this->url('editor', array('action' => 'add')));
 					$form->setAttribute('class', 'form-horizontal');
 					$form->setAttribute('style', 'border:1px solid #ccc; padding:15px;');
 					$form->setAttribute('name', 'editorForm');

 					$form->prepare();

					echo $this->form()->openTag($form);

					echo "<div class='form-group'>";
						echo "<label for='edit_id' class='col-sm-2 control-label'><span>ID: </span></label>";
						echo '<div class="col-sm-10">';

							echo $this->formRow($form->get('edit_id')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'ID de editor')->setAttribute('id', 'edit_id'));

						echo "</div>";
					echo "</div>";
					echo "<div class='form-group'>";
						echo "<label for='edit_nombre' class='col-sm-2 control-label'><span>Nombre: </span></label>";
							echo '<div class="col-sm-10">';

								echo $this->formRow($form->get('edit_nombre')->setAttribute('class', 'form-control')->setAttribute('placeholder', 'Nombre')->setAttribute('id', 'edit_nombre'));

							echo "</div>";
						echo "</div>";
					echo "<div class='form-group'>";
						echo "<div class='col-sm-offset-2 col-sm-10'>";

							echo $this->formSubmit($form->get('submit')->setAttribute('value', 'Añadir Editor'));

						echo "</div>";
					echo "</div>";

					echo $this->form()->closeTag();
                
                ?>
         	</div>
         </div>
        </div>
    </div>
