<div class="row">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Lista de Editores:</h1>
                <p>Aqui puedes visualizar todas las editoriales asociadas a los libros.</p>
                <p><a href="<?php echo $this->basePath('/editor/add') ?>"class="btn btn-primary btn-lg" href="#" role="button">Nueva Editorial</a>
            </div>

            <table class="table table-hover">
			 <tr>
			     <th>#</th>
			     <th>Nombre</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($editores as $editor) : ?>
			 <tr>
			     <td><?php echo $this->escapeHtml($editor->edit_id);?></td>
			     <td><?php echo $this->escapeHtml($editor->edit_nombre);?></td>

			    <td>
			        <a href="<?php echo $this->url('editor',
			            array('action'=>'edit', 'id' => $editor->edit_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->url('editor',
			            array('action'=>'delete', 'id' => $editor->edit_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			 <?php endforeach; ?>
			 </table>
        </div>
    </div>
