<?php
        if(session_start()!=null){
        
        if(isset($_SESSION['estatus']) && isset($_SESSION['email']) ){

?>

<?php echo $this->doctype(); ?>

<html lang="es_ES">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle("Biblioteca Universal")?>

        <?php echo $this->headMeta()
                     ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                     ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

          <!-- styles -->

        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/biblioteca-style.css')                      ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                                    
                                    ;
        ?>

        <?php echo $this->headScript()
                                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                ->prependFile($this->basePath() . '/js/jquery.min.js')
                                ->prependFile($this->basePath() . '/js/app.js')
                                ->prependFile($this->basePath() . '/js/angular.min.js') 
                              ;
        ?>

    </head>
   
<body ng-app="bibliotecaApp" >

<div class="wraper" >
    <div id="container-fluid">
        <div class="row">
            <nav class="navbar navbar-default" role="navigation" style="margin: 0 auto;">           <div class="container-fluid" style="background-color: #337AB7;">
                    <div class="container">
                        <div class="navbar-header">
                            <a href="<?php echo $this->basePath('/') ?>" class="navbar-brand">Inicio</a>
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                                <span class="sr-only">show navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav">
                            <li class="dropdown" id="Archivo">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" >Gestión<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">

                                <?php  if($_SESSION['estatus']=='administrador'){ ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('/prestamos/add') ?>">Iniciar Préstamos</a>
                                    </li>   
                                    <li>
                                        <a href="<?php echo $this->basePath('/prestamos/devolucion') ?>">Iniciar Devolucién</a>
                                    </li>
                                <?php } ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('/usuarios') ?>">Lista de Usuarios</a>
                                    </li>

                                    <li>
                                        <a href="" data-toggle="modal" data-target="#myModal">Datos de la Biblioteca</a>
                                    </li> 
                                    <li class="divider">
                                    </li>                 
                                    <li>
                                        <a href="<?php echo $this->basePath('/logout') ?>">Salir</a>
                                    </li>                                        
                                </ul>
                            </li>
                             <?php  if($_SESSION['estatus']=='administrador'){ ?>
                            <li class="dropdown" id="Libros">

                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mantenimiento<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="<?php echo $this->basePath('/libro') ?>">Lista de Libros <span class="glyphicon glyphicon-book"></span></a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('/autor') ?>">Lista de Autores <span class="glyphicon glyphicon-user"></span></a>
                                    </li>
                                    <li class="divider">
                                    </li>
                                     <li>
                                        <a href="<?php echo $this->basePath('/editor') ?>">Lista de Editores <span class="glyphicon glyphicon-pencil"></span></a>
                                    </li>    
                                    <li class="divider">
                                    </li>
                                     <li>
                                        <a href="<?php echo $this->basePath('/catedra') ?>">Lista de Catédras <span class="glyphicon glyphicon-tags"></span></a>
                                    </li>                                  
                                </ul>
                            </li>
                            <?php }  ?>
                            <li class="dropdown" id="Informes">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Busquedas<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">

                                    <?php  if($_SESSION['estatus']=='administrador'){ ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('/busquedas/alfabetica') ?>">Libros Alfabeticamente <span class="glyphicon glyphicon-font"></span></a>
                                    </li> 
                                    <li>
                                        <a href="<?php echo $this->basePath('/busquedas/autor') ?>">Libros por Autor <span class="glyphicon glyphicon-user"></a>
                                    </li>

                                     <li>
                                        <a href="<?php echo $this->basePath('/busquedas/catedra') ?>">Libros por Catédra <span class="glyphicon glyphicon-tags"></a>
                                    </li>

                                      <li> 
                                        <a href="<?php echo $this->basePath('/busquedas/barra') ?>">Libros por Codigo de Barra <span class="glyphicon glyphicon-barcode"></span></a>
                                    </li>

                                    <?php }else{ ?>

                                    <li>
                                        <a href="<?php echo $this->basePath('/busquedas/alfabetica_v') ?>">Libros Alfabeticamente <span class="glyphicon glyphicon-font"></span></a>
                                    </li>

                                    <li>
                                        <a href="<?php echo $this->basePath('/busquedas/autor_v') ?>">Libros por Autor <span class="glyphicon glyphicon-user"></a>
                                    </li>

                                    <li>
                                        <a href="<?php echo $this->basePath('/busquedas/catedra_v') ?>">Libros por Catédra <span class="glyphicon glyphicon-tags"></a>
                                    </li>

                                    <li> 
                                        <a href="<?php echo $this->basePath('/busquedas/barra_v') ?>">Libros por Codigo de Barra <span class="glyphicon glyphicon-barcode"></span></a>
                                    </li>

                                   <?php } ?>
                                  
                                    
                                     
                                  
                                </ul>
                            </li>
                            <li class="dropdown" id="Prestamos">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Préstamos y Sanciones<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="<?php echo $this->basePath('/prestamos/fechas') ?>">Ver Prestamos por Fecha</a>
                                    </li>

                                <?php  if($_SESSION['estatus']=='administrador'){ ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('/prestamos')?>">Modificar Préstamos</a>
                                    </li> 
                                <?php } ?>

                                    <li class="divider">
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath('/sanciones')?>">Ver Sanciones</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown" id="Web">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Web<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="">www.bibliotecaweb.com</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown" id="Herramientas">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reportes<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">

                                <?php  if($_SESSION['estatus']=='administrador'){ ?>
                                    <li>
                                        <a href="<?php echo $this->basePath('/libro/report')?>">Reporte de Libros</a>
                                    </li>
                                    <li class="divisor"></li>
                                    <li>
                                        <a href="<?php echo $this->basePath('/prestamos/report')?>">Reporte de Préstamos</a>
                                    </li>
                                     <li class="divisor"></li>
                                    <li>
                                        <a href="<?php echo $this->basePath('/empleados/report')?>">Reporte de Empleados</a>
                                    </li>
                                    <li class="divisor"></li>
                                    <li>
                                        <a href="">Configuración</a>
                                    </li>

                                <?php } ?>
                                    <!--<li>
                                        <a href="">Backup</a>
                                    </li>                               
                                    <li>
                                        <a href="">Restore</a>
                                    </li>-->
                                    
                                </ul>
                            </li>
                            <li class="dropdown" id="Ayuda">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ayuda<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="" data-toggle="modal" data-target="#myModal">Acerca de...</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>        
    </div>
</div>


    <div id="main" class="container" style="padding-bottom:150px; border:1px solid #eee;">

      <?php echo $this->content; ?>
     
    </div>

    <footer class="admin-footer">

        <p>Creado desde el año 2015 - @Copyright 2015 - <?php echo date('Y') ?></p>

    </footer>


    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Maria Quesada</h4>
      </div>
      <div class="modal-body">
       

       <div class="row">
        <div class="col-md-10 col-md-offset-2 col-xs-8">
            <h3>E.B.N. "Norman Prieto Ramos". </h3>
        </div>
        <div class="col-xs-4 col-md-offset-4 col-md-4">
            <a href="#" class="thumbnail">
            <img src="<?php echo $this->basePath('/img/escudo.png') ?>" alt="Escudo de la Institucion">
            </a>
        </div>
        </div>

       <p>Esta es la administración, de una simple biblioteca para todos. Múltiples libros, múltiples categorías, préstamos y mucho más.</p>


      </div>
      <div class="modal-footer">
         <p>Software version "beta". Ultima actualizacion: 08-04-2015</p>

      </div>
    </div>
  </div>
</div>

</div>

  <?php echo $this->inlineScript() ?>
</body>
</html>
<?php 
    
    }else{
            
            
        header('Location:'.$this->basePath('login'));
                        die('died');
        }
        
    }

 ?>