<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h2>¿Estas seguro de eliminar esta catedra?</h2>
                <p>Catedra #<?php echo $this->escapeHtml($this->cat_id); ?>
     			</p>
     			<p>Nombre: <?php echo $this->escapeHtml($catedra->cat_nombre); ?>. 
</p>

     			<?php 

				 	$url = $this->url('catedra', array(
				    'action' => 'delete',
				    'id'     => $this->cat_id,
				 	));

     			 ?>

     			<form action="<?php echo $url; ?>" method="post">
				 	<div>
				     	<input type="hidden" name="id" value="<?php echo (int) $catedra->cat_id; ?>" />
				     	<input type="submit" class="btn btn-primary" name="del" value="Yes" />
				     	<input type="submit" class="btn btn-default" name="del" value="No" />
				 	</div>
				</form>
            </div>	
        </div>
    </div>
