<div class="row">
        <div class="col-md-offset-1 col-md-10" style="">                
            <div class="jumbotron">
                <h1>Lista de Catédras:</h1>
                <p>Aqui podras visualizar todas las catédras que poseen los libros</p>
                <p><a class="btn btn-primary btn-lg" href="<?php echo $this->basePath('/catedra/add') ?>" role="button">Nueva Catedra</a>
            </div>

            <table class="table table-hover">
			 <tr>
			     <th>#</th>
			     <th>Nombre</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($catedras as $catedra) : ?>
			 <tr>
			     <td><?php echo $this->escapeHtml($catedra->cat_id);?></td>
			     <td><?php echo $this->escapeHtml($catedra->cat_nombre);?></td>

			    <td>
			        <a href="<?php echo $this->url('catedra',
			            array('action'=>'edit', 'id' => $catedra->cat_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
			        </a>
			    </td>
			    <td>
			     	<a href="<?php echo $this->url('catedra',
			            array('action'=>'delete', 'id' => $catedra->cat_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
			        </a>
			    </td>
			 </tr>
			 <?php endforeach; ?>
			 </table>
        </div>
    </div>
