<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Busqueda de libros:</h1>
                <p>Aqui podras visualizar todos los libros que posee la biblioteca</p>

                <form class="form-horizontal" action="<?php echo $this->basePath('/libro/resultados') ?>" method="POST">
                	<div class='form-group'>
						<div class="col-sm-4">
						<div class="form-inline">
							<input class="form-control" id="search" placeholder="NOMBRE" maxlength="56">
							<button class="btn btn-default" id="search_button">  <span class="glyphicon glyphicon-search"></span></button>
						</div>
						<div class="form-horizontal">
							<select class="form-control">
								<option value="" selected>Tipo de Busqueda</option> 
								<option value="libro">Libro</option>
								<option value="autor">Autor</option>
								<option value="editor">Editor</option>
								<option value="catedra">Catédra</option>
							</select>
						</div>

						</div>
					</div>
 				</form>
            </div>
	</div>
 </div>

