<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                
                 <h2>¿Estas seguro de eliminar este Libro?</h2>
                <p>Codigo de barra: #<?php echo $this->escapeHtml($this->libro_bar_id); ?>
     			</p>
     			<p>Nombre: <?php echo $this->escapeHtml($libro->libro_nombre); ?>. 
</p>

     			<?php 

				 	$url = $this->url('libro', array(
				    'action' => 'delete',
				    'id'     => $this->libro_bar_id,
				 	));

     			 ?>

     			<form action="<?php echo $url; ?>" method="post">
				 	<div>
				     	<input type="hidden" name="id" value="<?php echo (int) $libro->libro_bar_id; ?>" />
				     	<input type="submit" class="btn btn-primary" name="del" value="Eliminar" />
				     	<input type="submit" class="btn btn-default" name="del" value="Cancelar" />
				 	</div>
				</form>

            </div>
        </div>
    </div>
