<div class="row">
        <div class="col-md-12" style="">                
            <div class="jumbotron">
                <h1>Lista de libros:</h1>
                <p>Aqui podras visualizar todos los libros que posee la biblioteca</p>
                <p><a href="<?php echo $this->basePath('/libro/add') ?>" class="btn btn-primary btn-lg" href="#" role="button">Nuevo Libro</a></p>
            </div>

			<table class="table table-hover">
			 <tr>
			     <th>Codigo Barra</th>
			     <th>Nombre</th>
			     <th>Autor</th>
			     <th>Editorial</th>
			     <th>Catedra</th>
			     <th>Cantidad</th>
			     <th>Fecha de registro</th>
			     <th>Reseña</th>
			     <th>Editar</th>
			     <th>Eliminar</th>
			 </tr>
			 <?php foreach ($this->paginator as $libro) : ?>

			 <tr>

			     <td><?php echo $this->escapeHtml($libro->libro_bar_id);?></td>
			     <td>
			     	<a href="<?php echo $this->basePath('libro/details/').$libro->libro_bar_id ?>">
			         <?php echo $this->escapeHtml($libro->libro_nombre);?>
			        </a>
			     </td>
			     <td><?php echo $this->escapeHtml($libro->aut_nombre);?></td>
			     <td><?php echo $this->escapeHtml($libro->edit_nombre);?></td>
			     <td><?php echo $this->escapeHtml($libro->catedra_nombre);?></td>
			     <td><?php echo $this->escapeHtml($libro->cantidad);?></td>
			     <td><?php echo $this->escapeHtml($libro->fecha_creacion);?></td>

			     <td>
			     	<a href="<?php echo $this->basePath('libro/details/').$libro->libro_bar_id ?>">Ver ficha del libro
			        </a>
			     </td>
			     <td>
			         <a href="<?php echo $this->url('libro',
			             array('action'=>'edit', 'id' => $libro->libro_bar_id));?>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
			     </td>
			     <td>
			     	  <a href="<?php echo $this->url('libro',
			             array('action'=>'delete', 'id' => $libro->libro_bar_id));?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a>
			     </td>
			 </tr>
			 <?php endforeach; ?> 
			 
			 </table>
       
 		
	</div>
	<div class="col-md-offset-5 col-md-3">
		<div class="center-block">

			 <?php
				 // add at the end of the file after the table
				 echo $this->paginationControl(
				     // the paginator object
				     $this->paginator,
				     // the scrolling style
				     'sliding',
				     // the partial to use to render the control
				     'partial/paginator.phtml',
				     // the route to link to when a user clicks a control link
				     array(
				         'route' => 'libro'
				     )
				 );
				 ?>
		</div>
	</div>
   </div>
